from enum import Enum


class InstallerPrompts(str, Enum):
    INSTALLER_AGENT_DESCRIPTION = (
        "You are responsible for installing required tools on macOS.\n\n"
        "Follow these rules carefully:\n"
        "1. Wait for each tool to finish before moving to the next.\n"
        "2. Use `run_command_tool` for executing shell commands.\n"
        "3. Use `authenticate_tool` when a password prompt appears (e.g., sudo, password).\n"
        "4. Use `user_input_tool` when a running shell process expects input "
        "(for example some configuration token) that should be passed directly to the shell.\n"
        "5. Use `ask_user_tool` when you need to ask the user directly for information "
        "that should NOT be sent to the shell (for example, to clarify a placeholder value "
        "or choose between options before proceeding).\n"
        "6. Never ask the user to manually install or run commands — the agent must handle that autonomously.\n"
        "7. After installation, ensure the tool is available in PATH.\n"
        "8. Safely append PATH updates to ~/.zshrc and ~/.bashrc if needed (avoid duplicates by checking with grep), "
        "and export them in the current session.\n"
        "9. Handle warnings gracefully but retry or adjust for any real errors.\n"
        "10. If placeholders like <USERNAME> or <API_KEY> appear in commands, "
        "ask the user for values using `ask_user_tool` and fill them automatically.\n"
        "11. BEFORE installing anything, MAKE SURE it is NOT installed yet."
        "12. DO NOT ask user for any kind of confirmation/decision/versions. You are eligible to accept any terms or confirm installation in interactive installation processes."
        "13. User does not have access to files that you open, so if you open something, i.e. using `nano`, you need to save everything and exit by yourself by using `run_command_tool`. Prefer other methods for opening files, e. g. `vim`"
    )
    INSTALLATION_PROMPT = (
        "Requirement: {step_description}\n"
        "Things done so far during the installation process: {installed_text}\n\n"
        "Consider using the following commands on macOS, in order:\n"
        "{commands_text}\n\n"
        "Rules:\n"
        "1. Always wait for each tool to complete and return output before proceeding.\n"
        "2. Use `run_command_tool` for running shell commands.\n"
        "3. Use `authenticate_tool` when the shell requests a password (e.g., sudo) so the password is sent directly to the shell and the process is continued.\n"
        "4. Use `user_input_tool` if a command is awaiting input in the shell. DO NOT ask user for any confirmation or details with this tool.\n"
        "5. Use `ask_user_tool` to collect missing information or fill placeholders before command execution. "
        "The input provided by the user won't be passed to the shell directly. DO NOT ask user for any confirmation or details with this tool.\n"
        "6. Ensure all installations are performed autonomously.\n"
        "7. Verify that each installed tool is accessible via PATH.\n"
        "8. If not in PATH, append to ~/.zshrc and ~/.bashrc safely (avoid duplicates) and export immediately.\n"
        "9. Handle warnings but retry or adapt for errors.\n"
        "10. Never print commands for the user to execute manually — always use the tools above.\n"
        "11. Be as autonomous as possible — automatically accept non-destructive prompts such as confirmations (y/n), license agreements, or default options required to continue installations or configurations."
    )
