from typing import Callable

from langchain.agents.middleware import AgentMiddleware, ModelRequest, ModelResponse


class ParallelToolCallsMiddleware(AgentMiddleware):
    """Middleware to configure parallel tool execution behavior for the agent.

    This middleware intercepts the model request and explicitly sets the
    `parallel_tool_calls` parameter in the model settings, enforcing whether
    the LLM is allowed to output multiple tool calls in a single turn.

    Most models enable parallel tool calls by default and only some model
    providers allow you to disable parallel tool calls (https://docs.langchain.com/oss/python/langchain/models#parallel-tool-calls)

    Attributes:
        parallel_tool_calls (bool): The desired configuration for parallel tool execution.
    """

    def __init__(self, parallel_tool_calls: bool = False) -> None:
        """Initializes the middleware with a specific parallel tool configuration.

        Args:
            parallel_tool_calls (bool): If True, allows the model to generate
                multiple tool calls in parallel. If False, restricts the model
                to sequential or single tool calls. Defaults to False.
        """
        self.parallel_tool_calls = parallel_tool_calls

    def wrap_model_call(
        self,
        request: ModelRequest,
        handler: Callable[[ModelRequest], ModelResponse],
    ) -> ModelResponse:
        """Intercepts the model call to inject the parallel_tool_calls setting.

        Copies the existing model settings from the request, updates the
        `parallel_tool_calls` key, and passes the modified request to the next
        handler in the chain.

        Args:
            request (ModelRequest): The incoming request containing messages and settings.
            handler (Callable[[ModelRequest], ModelResponse]): The next function in the
                middleware chain (or the final model call) to invoke.

        Returns:
            ModelResponse: The response generated by the model (or subsequent middleware).
        """
        model_settings = request.model_settings.copy()
        model_settings.update({"parallel_tool_calls": self.parallel_tool_calls})

        updated_request = request.override(model_settings=model_settings)

        return handler(updated_request)
