from enum import Enum


class WorkflowNode(str, Enum):
    PLANNER = "PLANNER_AGENT"
    INSTALLER = "INSTALLER_AGENT"
    RUNNER = "RUNNER_AGENT"
    GUIDELINES_RETRIEVER_NODE = "GUIDELINES_RETRIEVER_NODE"
