"""This plugin searches for GitLab tokens."""
import re
from typing import List, Pattern

from detect_secrets.plugins.base import RegexBasedDetector


class GitLabTokenDetector(RegexBasedDetector):
    """Scans for GitLab tokens.

    This detector identifies various GitLab token types (Personal Access Tokens,
    Deploy Tokens, Runner Tokens, etc.) based on their specific prefixes
    introduced to allow for secret scanning.
    """

    @property
    def secret_type(self) -> str:
        """Returns the secret type identifier.

        Returns:
            str: The string identifier 'GitLab Token'.
        """
        return 'GitLab Token'

    @property
    def denylist(self) -> List[Pattern]:
        """Returns the list of regex patterns to search for.

        This list covers a wide range of GitLab token formats, most of which follow
        the pattern `prefix-token`.

        Supported token types and prefixes:
        - Personal Access Token (`glpat-`): User authentication.
        - Deploy Token (`gldt-`): Repository access.
        - Feed Token (`glft-`): RSS/Atom feed access.
        - OAuth Access Token (`glsoat-`): OAuth flow.
        - Runner Token (`glrt-`): Runner authentication.
        - Runner Registration Token (`GR1348941`): Registering new runners.
        - CI/CD Job Token (`glcbt-`): Authentication within CI jobs.
        - Incoming Mail Token (`glimt-`): Email ingestion.
        - Pipeline Trigger Token (`glptt-`): Triggering pipelines.
        - Agent Token (`glagent-`): Kubernetes agent.
        - OAuth Application Secret (`gloas-`): OAuth app credentials.

        References:
            - https://docs.gitlab.com/ee/security/token_overview.html#gitlab-tokens
            - https://gitlab.com/groups/gitlab-org/-/epics/8923

        Returns:
            List[Pattern]: A list of compiled regular expression patterns.
        """
        return [
            # Personal Access Token, Deploy Token, Feed Token, OAuth Access Token, Runner Token
            # Expected length: 20-50 chars (alphanumeric, underscore, dash)
            re.compile(
                r'(glpat|gldt|glft|glsoat|glrt)-'
                r'[A-Za-z0-9_\-]{20,50}(?!\w)',
            ),

            # Runner Registration Token
            re.compile(r'GR1348941[A-Za-z0-9_\-]{20,50}(?!\w)'),

            # CI/CD Token - `glcbt` or `glcbt-XY_` where XY is a 2-char hex 'partition_id'
            re.compile(r'glcbt-([0-9a-fA-F]{2}_)?[A-Za-z0-9_\-]{20,50}(?!\w)'),

            # Incoming Mail Token - generated by SecureRandom.hex, default length 16 bytes
            # resulting token length is 26 when Base-36 encoded
            re.compile(r'glimt-[A-Za-z0-9_\-]{25}(?!\w)'),

            # Trigger Token - generated by `SecureRandom.hex(20)`
            re.compile(r'glptt-[A-Za-z0-9_\-]{40}(?!\w)'),

            # Agent Token - generated by `Devise.friendly_token(50)`
            # tokens have a minimum length of 50 chars, up to 1024 chars
            re.compile(r'glagent-[A-Za-z0-9_\-]{50,1024}(?!\w)'),

            # GitLab OAuth Application Secret - generated by `SecureRandom.hex(32)`
            # -> becomes 64 base64-encoded characters
            re.compile(r'gloas-[A-Za-z0-9_\-]{64}(?!\w)'),
        ]