"""This plugin searches for Telegram bot tokens."""
import re
from typing import List, Pattern

from detect_secrets.plugins.base import RegexBasedDetector


class TelegramBotTokenDetector(RegexBasedDetector):
    """Scans for Telegram Bot tokens.

    Telegram Bot tokens are generated by the 'BotFather' and serve as the
    authentication mechanism for the Telegram Bot API.
    """

    @property
    def secret_type(self) -> str:
        """Returns the secret type identifier.

        Returns:
            str: The string identifier 'Telegram Bot Token'.
        """
        return 'Telegram Bot Token'

    @property
    def denylist(self) -> List[Pattern]:
        """Returns the list of regex patterns to search for.

        The pattern enforces the standard Telegram token structure:
        1. Bot ID: 8 to 10 digits.
        2. Separator: Colon `:`.
        3. Secret: 35 alphanumeric characters (including `_` and `-`).

        Note:
            This regex uses start (^) and end ($) anchors, meaning it currently
            only detects tokens that occupy the entire analyzed string (e.g.,
            exact matches in a configuration file).

        Reference:
            https://core.telegram.org/bots/api#authorizing-your-bot

        Returns:
            List[Pattern]: A list of compiled regular expression patterns.
        """
        return [
            # refs https://core.telegram.org/bots/api#authorizing-your-bot
            re.compile(r'^\d{8,10}:[0-9A-Za-z_-]{35}$'),
        ]